configMapGenerator:
- files:
  - application.yml
  name: 82265627-configmap
  namespace: "82265627"
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: cepgstapacr.azurecr.io/82265627
  newTag: "202411010718" 