apiVersion : apps/v1
kind: Deployment
metadata:
  name: "82265627" 
  namespace: "82265627"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "82265627"
  template:
    metadata:
      labels:
        app: "82265627" 
    spec:
      containers:
        - name: "82265627" 
          image: cepgstapacr.azurecr.io/82265627
          ports:
          - containerPort: 8080